language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
compiler:
  - clang
install:
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=shellinford"
after_success:
  - coveralls
