language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
compiler:
  - clang
install:
  - "python setup.py install"
script:
  - nosetests
notifications:
  email:
    recipients:
      - yukino0131@me.com
    on_success: always
    on_failure: always
